### ISSUE TITLE
Expose onChangeInput to children through a callback

### ISSUE THREAD

**Issue by Hopp3r** [djorg83/react-bootstrap-sweetalert#70]
I'm new-ish to React, but is it possible to expose onChangeInput as a callback exposed to content/children, and update inputValue to instead be an object in the form of:
`inputValue: { elementOne: value, elementTwo: value, } `?

This would allow us to create mini-forms in our alert modals (more than 1 input), and update state regardless of the amount of inputs.
Therefore, `type='input'` wouldn't be the only way to pass values from modal state into onConfirm. 

```jsx
  onChangeInput = (e: React.ChangeEvent) => {
    const target = e.target as HTMLTextAreaElement|HTMLInputElement;
    this.setState({
      inputValue: target.value,
      showValidationMessage: false
    });
  };
```

Any input on this would be great. I wanted to get some feedback on this before doing any dev work. There might be an easier way than what I'm seeing.

Thanks!

**Comment by djorg83** [comment]
What about something like this?

- A new prop called `dependencies: any[]` is added.  Whenever this prop changes, the alert content will re-render.
- Add the ability to use a render prop so that you can call `onConfirm` when your form is submitted, and provide a `setAutoFocusInputRef` method so that you can designate an input element to receive the initial cursor/focus.
- You maintain control of your own validation and error message display

I think this would resolve issue #30 also.

``` tsx
const [firstName, setFirstName] = useState('');
const [lastName, setLastName] = useState('');

const errorMessage = validate(firstName, lastName);

<SweetAlert dependencies={[firstName, lastName]}>
  {(onConfirm, setAutoFocusInputRef) => (
    <form onSubmit={onConfirm}>
      {errorMessage && <div>Error! {errorMessage}</div>}
      <input ref={setAutoFocusInputRef} value={firstName} onChange={(e) => setFirstName(e.target.value)} />
      <input value={lastName} onChange={(e) => setLastName(e.target.value)} />
    </form>
  )}
</SweetAlert>
```

**Comment by Hopp3r** [comment]
This seems like a good implementation to me. Would you think `onConfirm={(response) => alert(response)}` should be altered so `response` maintains the user-defined state?
`

**Comment by djorg83** [comment]
> This seems like a good implementation to me. Would you think `onConfirm={(response) => this.onRecieveInput(response)}` should be altered so `response` maintains the user-defined state? (versus returning undefined since 'inputValue' will be undefined)

Sure.  I'll add a new `type` called `'controlled'`, where if `props.type === 'controlled'` then `props.onConfirm` will return `props.dependencies`.  Although, since you are managing the state externally, and passing them in as props, technically you already have these values.  But I'll add this in any case.

**Comment by Hopp3r** [comment]
I think that's a good idea. Thanks for the quick response btw, I appreciate the help on this issue! :)

**Comment by Hopp3r** [comment]
@djorg83 With the proposed implementation above you've given an example using children:
```jsx
<SweetAlert dependencies={[firstName, lastName]}>
  {(onConfirm, setAutoFocusInputRef) => (
    <form onSubmit={onConfirm}>
      {errorMessage && <div>Error! {errorMessage}</div>}
      <input ref={setAutoFocusInputRef} value={firstName} onChange={(e) => setFirstName(e.target.value)} />
      <input value={lastName} onChange={(e) => setLastName(e.target.value)} />
    </form>
  )}
</SweetAlert>
```
could the same be done using the `content` prop? If so, how would that look?

```jsx
 <SweetAlert
    id: 'example',
   content:(  <form> <input/> </form> )
>
</SweetAlert>
```

**Comment by djorg83** [comment]
The content props was deprecated a while ago.

**Comment by Hopp3r** [comment]
Unrelated to this issue (we can continue this conversation elsewhere if you'd like) , but in your redux demo where you've put the SweetAlerts in state, you use:
```jsx
const App = ({ visibleAlert }) => (
  <ConnectedRouter history={history}>
    <div style={{ width: '100%', height: '100%' }}>
      <HeaderContainer />
      <Switch>
        <Route path='/' exact component={HomeContainer} />
        <Route component={NoMatch} />
      </Switch>
      {visibleAlert && <SweetAlert {...visibleAlert}>{visibleAlert.content}</SweetAlert>}
      <Footer/>
    </div>
  </ConnectedRouter>
);
```
How would you alter: `<SweetAlert {...visibleAlert}>{visibleAlert.content}</SweetAlert>` (specifically `visibleAlert.content`) to keep the 'props.children' style as opposed to having a content prop?

**Comment by djorg83** [comment]
The Alert object stored in the Store of that example extends SweetAlert props to have a `content` attribute.  As you can see, the content is still passed as `children` to the `<SweetAlert>` component.   If you are following this example, then with the new proposed solution discussed in this thread, you can just as easily make `content` a function instead of a react node.

**Comment by Hopp3r** [comment]
Do you have a timeline for potential release of this future? Just trying to estimate for sprint deadlines/feature requests.

**Comment by djorg83** [comment]
I have this done by next monday.

**Comment by djorg83** [comment]
`v5.2.0` is now available, and has this new feature.
